spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/pg-motos?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    show-sql: true
    open-in-view: true
    hibernate:
      ddl-auto: create